### ISSUE TITLE
Doxygen 1.9.3 not avialable due to SHA mismatch in CI

### ISSUE THREAD

**Issue by MuellerSeb** [conda-forge/doxygen-feedstock#26]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
The CI for this feedstock failed after merging #25 due to a SHA mismatch:
```bash
RuntimeError: SHA256 mismatch: 'eeee71516ddb0d8c057480c2fcd094e63b639146d09ba70b6fd013ca48a25b6a' != 'adcd968e10f27a15c956aaad86f544174f0e3d2d26d8d978929513ceeb09c19d'
```

**Comment by MuellerSeb** [comment]
Maybe this was because the src file was altered afterwards as stated [here](https://www.doxygen.nl/download.html#srcbin):
> The latest version of doxygen is 1.9.3 (release date 31 december 2021, updated 3th of January 2022).

**Comment by VincentRouvreau** [comment]
Even if the conda package failed for Windows, I think we can close this issue thanks to #30
