### ISSUE TITLE
[Patch] 1.9.7 Broken Markdown Support for Main Page

### ISSUE THREAD

**Issue by ax3l** [conda-forge/doxygen-feedstock#44]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Please see this upstream issue: https://github.com/doxygen/doxygen/issues/10110

and this patch: https://github.com/doxygen/doxygen/pull/10112

### Installed packages

```shell
doxygen 1.9.7 is broken

1.9.6 is fine.
```

Regression to #43

### Environment info

```shell
pure doxygen install from CF
```

**Comment by tdegeus** [comment]
I'm not opposed to release a 1.9.7 patch (though one should always strike a balance between patching and waiting for a patch release). If this is important to you you are welcome to open a PR

**Comment by ax3l** [comment]
Thanks @tdegeus!
I opened #45 and it is ready for merge :)
