### ISSUE TITLE
Please upgrade to 1.8.16

### ISSUE THREAD

**Issue by zhihaoy** [conda-forge/doxygen-feedstock#9]
1.8.15 was released last year, and 1.8.16 has just been released.

https://github.com/doxygen/doxygen/releases

**Comment by isuruf** [comment]
Please send a PR.

**Comment by tadeu** [comment]
I'll try to update it in this old PR: https://github.com/conda-forge/doxygen-feedstock/pull/8

**Comment by tadeu** [comment]
Resolved in #8
